//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuyenSinhWinApp.TuyenSinhServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TuyenSinhServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        TuyenSinhServiceLib.KetQuaDangNhap DangNhap(string tenDangNhap, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaDangNhap> DangNhapAsync(string tenDangNhap, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHocSinh", ReplyAction="http://tempuri.org/IService1/ThemHocSinhResponse")]
        TuyenSinhServiceLib.KetQuaThemHocSinh ThemHocSinh(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHocSinh", ReplyAction="http://tempuri.org/IService1/ThemHocSinhResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaThemHocSinh> ThemHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinh", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhResponse")]
        TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinh(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinh", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatHocSinhResponse")]
        bool CapNhatHocSinh(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatHocSinhResponse")]
        System.Threading.Tasks.Task<bool> CapNhatHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaHocSinh", ReplyAction="http://tempuri.org/IService1/XoaHocSinhResponse")]
        bool XoaHocSinh(int maHocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaHocSinh", ReplyAction="http://tempuri.org/IService1/XoaHocSinhResponse")]
        System.Threading.Tasks.Task<bool> XoaHocSinhAsync(int maHocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiaPhongThi", ReplyAction="http://tempuri.org/IService1/ChiaPhongThiResponse")]
        bool ChiaPhongThi(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiaPhongThi", ReplyAction="http://tempuri.org/IService1/ChiaPhongThiResponse")]
        System.Threading.Tasks.Task<bool> ChiaPhongThiAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/LayDanhSachPhongThiResponse")]
        TuyenSinhServiceLib.PhongThi[] LayDanhSachPhongThi(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/LayDanhSachPhongThiResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> LayDanhSachPhongThiAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhongResponse")]
        TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinhTheoPhong(string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhTheoPhongAsync(string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachDotTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachDotTuyenResponse")]
        TuyenSinhServiceLib.DotTuyenSinh[] LayDanhSachDotTuyen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachDotTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachDotTuyenResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.DotTuyenSinh[]> LayDanhSachDotTuyenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDotTuyen", ReplyAction="http://tempuri.org/IService1/ThemDotTuyenResponse")]
        bool ThemDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDotTuyen", ReplyAction="http://tempuri.org/IService1/ThemDotTuyenResponse")]
        System.Threading.Tasks.Task<bool> ThemDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DongDotTuyen", ReplyAction="http://tempuri.org/IService1/DongDotTuyenResponse")]
        bool DongDotTuyen(string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DongDotTuyen", ReplyAction="http://tempuri.org/IService1/DongDotTuyenResponse")]
        System.Threading.Tasks.Task<bool> DongDotTuyenAsync(string maDot);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TuyenSinhWinApp.TuyenSinhServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TuyenSinhWinApp.TuyenSinhServiceReference.IService1>, TuyenSinhWinApp.TuyenSinhServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TuyenSinhServiceLib.KetQuaDangNhap DangNhap(string tenDangNhap, string matKhau) {
            return base.Channel.DangNhap(tenDangNhap, matKhau);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaDangNhap> DangNhapAsync(string tenDangNhap, string matKhau) {
            return base.Channel.DangNhapAsync(tenDangNhap, matKhau);
        }
        
        public TuyenSinhServiceLib.KetQuaThemHocSinh ThemHocSinh(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.ThemHocSinh(hocSinh);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaThemHocSinh> ThemHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.ThemHocSinhAsync(hocSinh);
        }
        
        public TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinh(string maTruong) {
            return base.Channel.LayDanhSachHocSinh(maTruong);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhAsync(string maTruong) {
            return base.Channel.LayDanhSachHocSinhAsync(maTruong);
        }
        
        public bool CapNhatHocSinh(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.CapNhatHocSinh(hocSinh);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.CapNhatHocSinhAsync(hocSinh);
        }
        
        public bool XoaHocSinh(int maHocSinh) {
            return base.Channel.XoaHocSinh(maHocSinh);
        }
        
        public System.Threading.Tasks.Task<bool> XoaHocSinhAsync(int maHocSinh) {
            return base.Channel.XoaHocSinhAsync(maHocSinh);
        }
        
        public bool ChiaPhongThi(string maTruong) {
            return base.Channel.ChiaPhongThi(maTruong);
        }
        
        public System.Threading.Tasks.Task<bool> ChiaPhongThiAsync(string maTruong) {
            return base.Channel.ChiaPhongThiAsync(maTruong);
        }
        
        public TuyenSinhServiceLib.PhongThi[] LayDanhSachPhongThi(string maTruong) {
            return base.Channel.LayDanhSachPhongThi(maTruong);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> LayDanhSachPhongThiAsync(string maTruong) {
            return base.Channel.LayDanhSachPhongThiAsync(maTruong);
        }
        
        public TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinhTheoPhong(string maPhongThi) {
            return base.Channel.LayDanhSachHocSinhTheoPhong(maPhongThi);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhTheoPhongAsync(string maPhongThi) {
            return base.Channel.LayDanhSachHocSinhTheoPhongAsync(maPhongThi);
        }
        
        public TuyenSinhServiceLib.DotTuyenSinh[] LayDanhSachDotTuyen() {
            return base.Channel.LayDanhSachDotTuyen();
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.DotTuyenSinh[]> LayDanhSachDotTuyenAsync() {
            return base.Channel.LayDanhSachDotTuyenAsync();
        }
        
        public bool ThemDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.ThemDotTuyen(dot);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.ThemDotTuyenAsync(dot);
        }
        
        public bool DongDotTuyen(string maDot) {
            return base.Channel.DongDotTuyen(maDot);
        }
        
        public System.Threading.Tasks.Task<bool> DongDotTuyenAsync(string maDot) {
            return base.Channel.DongDotTuyenAsync(maDot);
        }
    }
}
