//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuyenSinhWinApp.TuyenSinhServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TuyenSinhServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        TuyenSinhServiceLib.KetQuaDangNhap DangNhap(string tenDangNhap, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DangNhap", ReplyAction="http://tempuri.org/IService1/DangNhapResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaDangNhap> DangNhapAsync(string tenDangNhap, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHocSinh", ReplyAction="http://tempuri.org/IService1/ThemHocSinhResponse")]
        TuyenSinhServiceLib.KetQuaThemHocSinh ThemHocSinh(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemHocSinh", ReplyAction="http://tempuri.org/IService1/ThemHocSinhResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaThemHocSinh> ThemHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinh", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhResponse")]
        TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinh(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinh", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GanMaSoBaoDanhHangLoat", ReplyAction="http://tempuri.org/IService1/GanMaSoBaoDanhHangLoatResponse")]
        void GanMaSoBaoDanhHangLoat(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GanMaSoBaoDanhHangLoat", ReplyAction="http://tempuri.org/IService1/GanMaSoBaoDanhHangLoatResponse")]
        System.Threading.Tasks.Task GanMaSoBaoDanhHangLoatAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatHocSinhResponse")]
        bool CapNhatHocSinh(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatHocSinhResponse")]
        System.Threading.Tasks.Task<bool> CapNhatHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDiemHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatDiemHocSinhResponse")]
        bool CapNhatDiemHocSinh(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDiemHocSinh", ReplyAction="http://tempuri.org/IService1/CapNhatDiemHocSinhResponse")]
        System.Threading.Tasks.Task<bool> CapNhatDiemHocSinhAsync(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaHocSinh", ReplyAction="http://tempuri.org/IService1/XoaHocSinhResponse")]
        bool XoaHocSinh(int maHocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaHocSinh", ReplyAction="http://tempuri.org/IService1/XoaHocSinhResponse")]
        System.Threading.Tasks.Task<bool> XoaHocSinhAsync(int maHocSinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiaPhongThi", ReplyAction="http://tempuri.org/IService1/ChiaPhongThiResponse")]
        bool ChiaPhongThi(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChiaPhongThi", ReplyAction="http://tempuri.org/IService1/ChiaPhongThiResponse")]
        System.Threading.Tasks.Task<bool> ChiaPhongThiAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/LayDanhSachPhongThiResponse")]
        TuyenSinhServiceLib.PhongThi[] LayDanhSachPhongThi(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/LayDanhSachPhongThiResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> LayDanhSachPhongThiAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhongResponse")]
        TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinhTheoPhong(string maTruong, string maDot, string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/LayDanhSachHocSinhTheoPhongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhTheoPhongAsync(string maTruong, string maDot, string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachDotTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachDotTuyenResponse")]
        TuyenSinhServiceLib.DotTuyenSinh[] LayDanhSachDotTuyen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachDotTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachDotTuyenResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.DotTuyenSinh[]> LayDanhSachDotTuyenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDotTuyen", ReplyAction="http://tempuri.org/IService1/ThemDotTuyenResponse")]
        bool ThemDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemDotTuyen", ReplyAction="http://tempuri.org/IService1/ThemDotTuyenResponse")]
        System.Threading.Tasks.Task<bool> ThemDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DongDotTuyen", ReplyAction="http://tempuri.org/IService1/DongDotTuyenResponse")]
        bool DongDotTuyen(string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DongDotTuyen", ReplyAction="http://tempuri.org/IService1/DongDotTuyenResponse")]
        System.Threading.Tasks.Task<bool> DongDotTuyenAsync(string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDotTuyen", ReplyAction="http://tempuri.org/IService1/CapNhatDotTuyenResponse")]
        bool CapNhatDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDotTuyen", ReplyAction="http://tempuri.org/IService1/CapNhatDotTuyenResponse")]
        System.Threading.Tasks.Task<bool> CapNhatDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatGiamThi", ReplyAction="http://tempuri.org/IService1/CapNhatGiamThiResponse")]
        void CapNhatGiamThi(string maPhong, string giamThi1, string giamThi2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatGiamThi", ReplyAction="http://tempuri.org/IService1/CapNhatGiamThiResponse")]
        System.Threading.Tasks.Task CapNhatGiamThiAsync(string maPhong, string giamThi1, string giamThi2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDiemTheoMon", ReplyAction="http://tempuri.org/IService1/CapNhatDiemTheoMonResponse")]
        bool CapNhatDiemTheoMon(int maHocSinh, string tenMon, string diemText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatDiemTheoMon", ReplyAction="http://tempuri.org/IService1/CapNhatDiemTheoMonResponse")]
        System.Threading.Tasks.Task<bool> CapNhatDiemTheoMonAsync(int maHocSinh, string tenMon, string diemText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayChiTieuTruong", ReplyAction="http://tempuri.org/IService1/LayChiTieuTruongResponse")]
        TuyenSinhServiceLib.ChiTieuTuyenSinh LayChiTieuTruong(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayChiTieuTruong", ReplyAction="http://tempuri.org/IService1/LayChiTieuTruongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.ChiTieuTuyenSinh> LayChiTieuTruongAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatChiTieu", ReplyAction="http://tempuri.org/IService1/CapNhatChiTieuResponse")]
        bool CapNhatChiTieu(string maTruong, string maDot, int chiTieu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatChiTieu", ReplyAction="http://tempuri.org/IService1/CapNhatChiTieuResponse")]
        System.Threading.Tasks.Task<bool> CapNhatChiTieuAsync(string maTruong, string maDot, int chiTieu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XetTrungTuyen", ReplyAction="http://tempuri.org/IService1/XetTrungTuyenResponse")]
        bool XetTrungTuyen(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XetTrungTuyen", ReplyAction="http://tempuri.org/IService1/XetTrungTuyenResponse")]
        System.Threading.Tasks.Task<bool> XetTrungTuyenAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachTrungTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachTrungTuyenResponse")]
        TuyenSinhServiceLib.HocSinh[] LayDanhSachTrungTuyen(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachTrungTuyen", ReplyAction="http://tempuri.org/IService1/LayDanhSachTrungTuyenResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachTrungTuyenAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeDiemTheoMon", ReplyAction="http://tempuri.org/IService1/ThongKeDiemTheoMonResponse")]
        TuyenSinhServiceLib.ThongKeDiemMon[] ThongKeDiemTheoMon(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeDiemTheoMon", ReplyAction="http://tempuri.org/IService1/ThongKeDiemTheoMonResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.ThongKeDiemMon[]> ThongKeDiemTheoMonAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeTheoTHCS", ReplyAction="http://tempuri.org/IService1/ThongKeTheoTHCSResponse")]
        TuyenSinhServiceLib.ThongKeTHCSRow[] ThongKeTheoTHCS(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeTheoTHCS", ReplyAction="http://tempuri.org/IService1/ThongKeTheoTHCSResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.ThongKeTHCSRow[]> ThongKeTheoTHCSAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeVangThi", ReplyAction="http://tempuri.org/IService1/ThongKeVangThiResponse")]
        TuyenSinhServiceLib.VangThiResult ThongKeVangThi(string maDot, string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThongKeVangThi", ReplyAction="http://tempuri.org/IService1/ThongKeVangThiResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.VangThiResult> ThongKeVangThiAsync(string maDot, string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachTruong", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachTruongResponse")]
        TuyenSinhServiceLib.TruongItem[] Admin_LayDanhSachTruong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachTruong", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachTruongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.TruongItem[]> Admin_LayDanhSachTruongAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoTruongDot", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoTruongDotResponse")]
        TuyenSinhServiceLib.HocSinh[] Admin_LayDanhSachHocSinhTheoTruongDot(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoTruongDot", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoTruongDotResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> Admin_LayDanhSachHocSinhTheoTruongDotAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoPhongResponse")]
        TuyenSinhServiceLib.HocSinh[] Admin_LayDanhSachHocSinhTheoPhong(string maTruong, string maDot, string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoPhong", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachHocSinhTheoPhongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> Admin_LayDanhSachHocSinhTheoPhongAsync(string maTruong, string maDot, string maPhongThi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_CapNhatDiemHocSinh", ReplyAction="http://tempuri.org/IService1/Admin_CapNhatDiemHocSinhResponse")]
        bool Admin_CapNhatDiemHocSinh(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_CapNhatDiemHocSinh", ReplyAction="http://tempuri.org/IService1/Admin_CapNhatDiemHocSinhResponse")]
        System.Threading.Tasks.Task<bool> Admin_CapNhatDiemHocSinhAsync(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachPhongThiResponse")]
        TuyenSinhServiceLib.PhongThi[] Admin_LayDanhSachPhongThi(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Admin_LayDanhSachPhongThi", ReplyAction="http://tempuri.org/IService1/Admin_LayDanhSachPhongThiResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> Admin_LayDanhSachPhongThiAsync(string maTruong, string maDot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachNguoiDungTheoTruong", ReplyAction="http://tempuri.org/IService1/LayDanhSachNguoiDungTheoTruongResponse")]
        TuyenSinhServiceLib.NguoiDung[] LayDanhSachNguoiDungTheoTruong(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachNguoiDungTheoTruong", ReplyAction="http://tempuri.org/IService1/LayDanhSachNguoiDungTheoTruongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.NguoiDung[]> LayDanhSachNguoiDungTheoTruongAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemNguoiDung", ReplyAction="http://tempuri.org/IService1/ThemNguoiDungResponse")]
        bool ThemNguoiDung(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemNguoiDung", ReplyAction="http://tempuri.org/IService1/ThemNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> ThemNguoiDungAsync(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhau);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatNguoiDung", ReplyAction="http://tempuri.org/IService1/CapNhatNguoiDungResponse")]
        bool CapNhatNguoiDung(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhauMoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatNguoiDung", ReplyAction="http://tempuri.org/IService1/CapNhatNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> CapNhatNguoiDungAsync(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhauMoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaNguoiDung", ReplyAction="http://tempuri.org/IService1/XoaNguoiDungResponse")]
        bool XoaNguoiDung(int maNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaNguoiDung", ReplyAction="http://tempuri.org/IService1/XoaNguoiDungResponse")]
        System.Threading.Tasks.Task<bool> XoaNguoiDungAsync(int maNguoiDung);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraTruongTonTai", ReplyAction="http://tempuri.org/IService1/KiemTraTruongTonTaiResponse")]
        bool KiemTraTruongTonTai(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KiemTraTruongTonTai", ReplyAction="http://tempuri.org/IService1/KiemTraTruongTonTaiResponse")]
        System.Threading.Tasks.Task<bool> KiemTraTruongTonTaiAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemTruong", ReplyAction="http://tempuri.org/IService1/ThemTruongResponse")]
        bool ThemTruong(TuyenSinhServiceLib.TruongHoc truong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThemTruong", ReplyAction="http://tempuri.org/IService1/ThemTruongResponse")]
        System.Threading.Tasks.Task<bool> ThemTruongAsync(TuyenSinhServiceLib.TruongHoc truong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTenTruongFromMaTruong", ReplyAction="http://tempuri.org/IService1/GetTenTruongFromMaTruongResponse")]
        string GetTenTruongFromMaTruong(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTenTruongFromMaTruong", ReplyAction="http://tempuri.org/IService1/GetTenTruongFromMaTruongResponse")]
        System.Threading.Tasks.Task<string> GetTenTruongFromMaTruongAsync(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachTruong", ReplyAction="http://tempuri.org/IService1/LayDanhSachTruongResponse")]
        TuyenSinhServiceLib.TruongHoc[] LayDanhSachTruong();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LayDanhSachTruong", ReplyAction="http://tempuri.org/IService1/LayDanhSachTruongResponse")]
        System.Threading.Tasks.Task<TuyenSinhServiceLib.TruongHoc[]> LayDanhSachTruongAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatTruong", ReplyAction="http://tempuri.org/IService1/CapNhatTruongResponse")]
        bool CapNhatTruong(TuyenSinhServiceLib.TruongHoc truong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CapNhatTruong", ReplyAction="http://tempuri.org/IService1/CapNhatTruongResponse")]
        System.Threading.Tasks.Task<bool> CapNhatTruongAsync(TuyenSinhServiceLib.TruongHoc truong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaTruong", ReplyAction="http://tempuri.org/IService1/XoaTruongResponse")]
        bool XoaTruong(string maTruong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XoaTruong", ReplyAction="http://tempuri.org/IService1/XoaTruongResponse")]
        System.Threading.Tasks.Task<bool> XoaTruongAsync(string maTruong);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TuyenSinhWinApp.TuyenSinhServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TuyenSinhWinApp.TuyenSinhServiceReference.IService1>, TuyenSinhWinApp.TuyenSinhServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TuyenSinhServiceLib.KetQuaDangNhap DangNhap(string tenDangNhap, string matKhau) {
            return base.Channel.DangNhap(tenDangNhap, matKhau);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaDangNhap> DangNhapAsync(string tenDangNhap, string matKhau) {
            return base.Channel.DangNhapAsync(tenDangNhap, matKhau);
        }
        
        public TuyenSinhServiceLib.KetQuaThemHocSinh ThemHocSinh(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.ThemHocSinh(hocSinh);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.KetQuaThemHocSinh> ThemHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.ThemHocSinhAsync(hocSinh);
        }
        
        public TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinh(string maTruong, string maDot) {
            return base.Channel.LayDanhSachHocSinh(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhAsync(string maTruong, string maDot) {
            return base.Channel.LayDanhSachHocSinhAsync(maTruong, maDot);
        }
        
        public void GanMaSoBaoDanhHangLoat(string maTruong, string maDot) {
            base.Channel.GanMaSoBaoDanhHangLoat(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task GanMaSoBaoDanhHangLoatAsync(string maTruong, string maDot) {
            return base.Channel.GanMaSoBaoDanhHangLoatAsync(maTruong, maDot);
        }
        
        public bool CapNhatHocSinh(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.CapNhatHocSinh(hocSinh);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatHocSinhAsync(TuyenSinhServiceLib.HocSinh hocSinh) {
            return base.Channel.CapNhatHocSinhAsync(hocSinh);
        }
        
        public bool CapNhatDiemHocSinh(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien) {
            return base.Channel.CapNhatDiemHocSinh(maHocSinh, diemToan, diemVan, diemAnh, diemKhuyenKhich, diemUuTien);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatDiemHocSinhAsync(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien) {
            return base.Channel.CapNhatDiemHocSinhAsync(maHocSinh, diemToan, diemVan, diemAnh, diemKhuyenKhich, diemUuTien);
        }
        
        public bool XoaHocSinh(int maHocSinh) {
            return base.Channel.XoaHocSinh(maHocSinh);
        }
        
        public System.Threading.Tasks.Task<bool> XoaHocSinhAsync(int maHocSinh) {
            return base.Channel.XoaHocSinhAsync(maHocSinh);
        }
        
        public bool ChiaPhongThi(string maTruong, string maDot) {
            return base.Channel.ChiaPhongThi(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<bool> ChiaPhongThiAsync(string maTruong, string maDot) {
            return base.Channel.ChiaPhongThiAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.PhongThi[] LayDanhSachPhongThi(string maTruong, string maDot) {
            return base.Channel.LayDanhSachPhongThi(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> LayDanhSachPhongThiAsync(string maTruong, string maDot) {
            return base.Channel.LayDanhSachPhongThiAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.HocSinh[] LayDanhSachHocSinhTheoPhong(string maTruong, string maDot, string maPhongThi) {
            return base.Channel.LayDanhSachHocSinhTheoPhong(maTruong, maDot, maPhongThi);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachHocSinhTheoPhongAsync(string maTruong, string maDot, string maPhongThi) {
            return base.Channel.LayDanhSachHocSinhTheoPhongAsync(maTruong, maDot, maPhongThi);
        }
        
        public TuyenSinhServiceLib.DotTuyenSinh[] LayDanhSachDotTuyen() {
            return base.Channel.LayDanhSachDotTuyen();
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.DotTuyenSinh[]> LayDanhSachDotTuyenAsync() {
            return base.Channel.LayDanhSachDotTuyenAsync();
        }
        
        public bool ThemDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.ThemDotTuyen(dot);
        }
        
        public System.Threading.Tasks.Task<bool> ThemDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.ThemDotTuyenAsync(dot);
        }
        
        public bool DongDotTuyen(string maDot) {
            return base.Channel.DongDotTuyen(maDot);
        }
        
        public System.Threading.Tasks.Task<bool> DongDotTuyenAsync(string maDot) {
            return base.Channel.DongDotTuyenAsync(maDot);
        }
        
        public bool CapNhatDotTuyen(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.CapNhatDotTuyen(dot);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatDotTuyenAsync(TuyenSinhServiceLib.DotTuyenSinh dot) {
            return base.Channel.CapNhatDotTuyenAsync(dot);
        }
        
        public void CapNhatGiamThi(string maPhong, string giamThi1, string giamThi2) {
            base.Channel.CapNhatGiamThi(maPhong, giamThi1, giamThi2);
        }
        
        public System.Threading.Tasks.Task CapNhatGiamThiAsync(string maPhong, string giamThi1, string giamThi2) {
            return base.Channel.CapNhatGiamThiAsync(maPhong, giamThi1, giamThi2);
        }
        
        public bool CapNhatDiemTheoMon(int maHocSinh, string tenMon, string diemText) {
            return base.Channel.CapNhatDiemTheoMon(maHocSinh, tenMon, diemText);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatDiemTheoMonAsync(int maHocSinh, string tenMon, string diemText) {
            return base.Channel.CapNhatDiemTheoMonAsync(maHocSinh, tenMon, diemText);
        }
        
        public TuyenSinhServiceLib.ChiTieuTuyenSinh LayChiTieuTruong(string maTruong, string maDot) {
            return base.Channel.LayChiTieuTruong(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.ChiTieuTuyenSinh> LayChiTieuTruongAsync(string maTruong, string maDot) {
            return base.Channel.LayChiTieuTruongAsync(maTruong, maDot);
        }
        
        public bool CapNhatChiTieu(string maTruong, string maDot, int chiTieu) {
            return base.Channel.CapNhatChiTieu(maTruong, maDot, chiTieu);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatChiTieuAsync(string maTruong, string maDot, int chiTieu) {
            return base.Channel.CapNhatChiTieuAsync(maTruong, maDot, chiTieu);
        }
        
        public bool XetTrungTuyen(string maTruong, string maDot) {
            return base.Channel.XetTrungTuyen(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<bool> XetTrungTuyenAsync(string maTruong, string maDot) {
            return base.Channel.XetTrungTuyenAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.HocSinh[] LayDanhSachTrungTuyen(string maTruong, string maDot) {
            return base.Channel.LayDanhSachTrungTuyen(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> LayDanhSachTrungTuyenAsync(string maTruong, string maDot) {
            return base.Channel.LayDanhSachTrungTuyenAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.ThongKeDiemMon[] ThongKeDiemTheoMon(string maTruong, string maDot) {
            return base.Channel.ThongKeDiemTheoMon(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.ThongKeDiemMon[]> ThongKeDiemTheoMonAsync(string maTruong, string maDot) {
            return base.Channel.ThongKeDiemTheoMonAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.ThongKeTHCSRow[] ThongKeTheoTHCS(string maTruong, string maDot) {
            return base.Channel.ThongKeTheoTHCS(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.ThongKeTHCSRow[]> ThongKeTheoTHCSAsync(string maTruong, string maDot) {
            return base.Channel.ThongKeTheoTHCSAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.VangThiResult ThongKeVangThi(string maDot, string maTruong) {
            return base.Channel.ThongKeVangThi(maDot, maTruong);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.VangThiResult> ThongKeVangThiAsync(string maDot, string maTruong) {
            return base.Channel.ThongKeVangThiAsync(maDot, maTruong);
        }
        
        public TuyenSinhServiceLib.TruongItem[] Admin_LayDanhSachTruong() {
            return base.Channel.Admin_LayDanhSachTruong();
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.TruongItem[]> Admin_LayDanhSachTruongAsync() {
            return base.Channel.Admin_LayDanhSachTruongAsync();
        }
        
        public TuyenSinhServiceLib.HocSinh[] Admin_LayDanhSachHocSinhTheoTruongDot(string maTruong, string maDot) {
            return base.Channel.Admin_LayDanhSachHocSinhTheoTruongDot(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> Admin_LayDanhSachHocSinhTheoTruongDotAsync(string maTruong, string maDot) {
            return base.Channel.Admin_LayDanhSachHocSinhTheoTruongDotAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.HocSinh[] Admin_LayDanhSachHocSinhTheoPhong(string maTruong, string maDot, string maPhongThi) {
            return base.Channel.Admin_LayDanhSachHocSinhTheoPhong(maTruong, maDot, maPhongThi);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.HocSinh[]> Admin_LayDanhSachHocSinhTheoPhongAsync(string maTruong, string maDot, string maPhongThi) {
            return base.Channel.Admin_LayDanhSachHocSinhTheoPhongAsync(maTruong, maDot, maPhongThi);
        }
        
        public bool Admin_CapNhatDiemHocSinh(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien) {
            return base.Channel.Admin_CapNhatDiemHocSinh(maHocSinh, diemToan, diemVan, diemAnh, diemKhuyenKhich, diemUuTien);
        }
        
        public System.Threading.Tasks.Task<bool> Admin_CapNhatDiemHocSinhAsync(int maHocSinh, string diemToan, string diemVan, string diemAnh, System.Nullable<decimal> diemKhuyenKhich, System.Nullable<decimal> diemUuTien) {
            return base.Channel.Admin_CapNhatDiemHocSinhAsync(maHocSinh, diemToan, diemVan, diemAnh, diemKhuyenKhich, diemUuTien);
        }
        
        public TuyenSinhServiceLib.PhongThi[] Admin_LayDanhSachPhongThi(string maTruong, string maDot) {
            return base.Channel.Admin_LayDanhSachPhongThi(maTruong, maDot);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.PhongThi[]> Admin_LayDanhSachPhongThiAsync(string maTruong, string maDot) {
            return base.Channel.Admin_LayDanhSachPhongThiAsync(maTruong, maDot);
        }
        
        public TuyenSinhServiceLib.NguoiDung[] LayDanhSachNguoiDungTheoTruong(string maTruong) {
            return base.Channel.LayDanhSachNguoiDungTheoTruong(maTruong);
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.NguoiDung[]> LayDanhSachNguoiDungTheoTruongAsync(string maTruong) {
            return base.Channel.LayDanhSachNguoiDungTheoTruongAsync(maTruong);
        }
        
        public bool ThemNguoiDung(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhau) {
            return base.Channel.ThemNguoiDung(nguoiDung, matKhau);
        }
        
        public System.Threading.Tasks.Task<bool> ThemNguoiDungAsync(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhau) {
            return base.Channel.ThemNguoiDungAsync(nguoiDung, matKhau);
        }
        
        public bool CapNhatNguoiDung(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhauMoi) {
            return base.Channel.CapNhatNguoiDung(nguoiDung, matKhauMoi);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatNguoiDungAsync(TuyenSinhServiceLib.NguoiDung nguoiDung, string matKhauMoi) {
            return base.Channel.CapNhatNguoiDungAsync(nguoiDung, matKhauMoi);
        }
        
        public bool XoaNguoiDung(int maNguoiDung) {
            return base.Channel.XoaNguoiDung(maNguoiDung);
        }
        
        public System.Threading.Tasks.Task<bool> XoaNguoiDungAsync(int maNguoiDung) {
            return base.Channel.XoaNguoiDungAsync(maNguoiDung);
        }
        
        public bool KiemTraTruongTonTai(string maTruong) {
            return base.Channel.KiemTraTruongTonTai(maTruong);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraTruongTonTaiAsync(string maTruong) {
            return base.Channel.KiemTraTruongTonTaiAsync(maTruong);
        }
        
        public bool ThemTruong(TuyenSinhServiceLib.TruongHoc truong) {
            return base.Channel.ThemTruong(truong);
        }
        
        public System.Threading.Tasks.Task<bool> ThemTruongAsync(TuyenSinhServiceLib.TruongHoc truong) {
            return base.Channel.ThemTruongAsync(truong);
        }
        
        public string GetTenTruongFromMaTruong(string maTruong) {
            return base.Channel.GetTenTruongFromMaTruong(maTruong);
        }
        
        public System.Threading.Tasks.Task<string> GetTenTruongFromMaTruongAsync(string maTruong) {
            return base.Channel.GetTenTruongFromMaTruongAsync(maTruong);
        }
        
        public TuyenSinhServiceLib.TruongHoc[] LayDanhSachTruong() {
            return base.Channel.LayDanhSachTruong();
        }
        
        public System.Threading.Tasks.Task<TuyenSinhServiceLib.TruongHoc[]> LayDanhSachTruongAsync() {
            return base.Channel.LayDanhSachTruongAsync();
        }
        
        public bool CapNhatTruong(TuyenSinhServiceLib.TruongHoc truong) {
            return base.Channel.CapNhatTruong(truong);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatTruongAsync(TuyenSinhServiceLib.TruongHoc truong) {
            return base.Channel.CapNhatTruongAsync(truong);
        }
        
        public bool XoaTruong(string maTruong) {
            return base.Channel.XoaTruong(maTruong);
        }
        
        public System.Threading.Tasks.Task<bool> XoaTruongAsync(string maTruong) {
            return base.Channel.XoaTruongAsync(maTruong);
        }
    }
}
